
replicaCount: 1
image:
  repository: app
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  port: 80

podAnnotations:
  service: mindbreez

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}

fluent:
  enabled: true

  luaScripts: {}
  podAnnotations: 
    fluentbit.io/exclude: "true"

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi

  logLevel: info
  metricsPort: 2020

  ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/configuration-file
  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush 5
          Log_Level info
          Parsers_File parsers.conf
          Parsers_File /fluent-bit/etc/custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port 2020
          Health_Check On

    ## https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
      [INPUT]
          Name tail
          Tag kube.*
          Path /var/log/containers/mindbreez-logs-discovery*.log
          multiline.parser multiline_parser, docker
          Mem_Buf_Limit 5MB
          Parser docker

      [INPUT]
          Name   dummy
          Tag    dummy.log
          Dummy  {}

    ## https://docs.fluentbit.io/manual/pipeline/filters
    filters: |
      [FILTER]
          Name             kubernetes
          Match            kube.*
          Kube_URL         https://kubernetes.default.svc:443
          Kube_Tag_Prefix  kube.var.log.containers.
          Kube_CA_File     /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
          Merge_Log        On
          Merge_Log_Key    log_processed
          K8S-Logging.Parser On
          K8S-Logging.Exclude On
          Labels On
          Annotations On


    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
      [OUTPUT]
          Name loki
          Match kube.*
          Host mindbreez-loki
          Port 3100
          labels job=fluentbit, pod=$kubernetes['pod_name'], namespace=$kubernetes['namespace_name'], host=$kubernetes['host'], container=$kubernetes['container_name']
          auto_kubernetes_labels on

      [OUTPUT]
          Name stdout
          Match kube.var.log.containers.mindbreez-logs-discovery*

    ## https://docs.fluentbit.io/manual/pipeline/parsers
    customParsers: |
      [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

      [PARSER]
        Name   app_parser
        Format regex
        Regex  ^(?<host>[^ ]*) - - \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) -$
        Types  status:integer

      [MULTILINE_PARSER]
        name          multiline_parser
        type          regex
        flush_timeout 1000
        #
        # Regex rules for multiline parsing
        # ---------------------------------
        #
        # configuration hints:
        #
        #  - first state always has the name: start_state
        #  - every field in the rule must be inside double quotes
        #
        # rules |   state name  | regex pattern                  | next state
        # ------|---------------|--------------------------------------------
        rule      "start_state"   "([^ ]*) - - \[([^\]]*)\].*-"  "cont"
        rule      "cont"          "^(?<header>[^:]*): (?<value>.*)$"                     "cont"

loki:
  enabled: true
  loki:
    enabled: true
    config:
      table_manager:
        retention_deletes_enabled: true
        retention_period: 2h
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "http-metrics"
      fluentbit.io/exclude: "true"
    persistence:
      enabled: true
      accessModes:
      - ReadWriteOnce
      size: 1Gi
      selector:
        matchLabels:
          lokivolume: "true"
      existingClaim: volume
  grafana:
    enabled: true
    replicas: 1
    sidecar:
      datasources:
        enabled: true
    adminUser: admin
    adminPassword: admin
  promtail:
    enabled: false
  prometheus:
    enabled: true
    alertmanager:
      enabled: false
    pushgateway:
      enabled: false
    nodeExporter:
      enabled: false
    serverFiles:
      prometheus.yml:
        rule_files:
          - /etc/config/recording_rules.yml
          - /etc/config/alerting_rules.yml
                
        scrape_configs:
          - job_name: prometheus
            static_configs:
              - targets:
                - localhost:9090
          - job_name: 'kubernetes-nodes-cadvisor'
            scheme: https
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            kubernetes_sd_configs:
              - role: node
            relabel_configs:
            - separator: ;
              regex: __meta_kubernetes_node_label_(beta_)*(.+)
              replacement: $2
              action: labelmap
            - separator: ;
              regex: (.*)
              target_label: __address__
              replacement: kubernetes.default.svc:443
              action: replace
            - source_labels: [__meta_kubernetes_node_name]
              separator: ;
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
              action: replace
            metric_relabel_configs:
            - source_labels: [container]
              regex: ^$
              action: drop
              
